spring:
  application:
    name: hello-world-ms

server:
  port: 8081

logging:
  level:
    root: info
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS}  [app:${spring.application.name},traceId:%X{X-B3-TraceId:-},spanId:%X{X-B3-SpanId:-},parentSpanId:%X{X-B3-ParentSpanId:-}] ${PID:-} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
